package bridge

import (
	"context"
	"errors"
	"strings"
	"sync"
	"time"

	"github.com/breakawaydata/orchard-gh-bridge/orchard"
)

// DefaultStateViewTTL is the maximum age of a Snapshot before Get triggers a refresh.
// 5s coalesces bursts (multiple scale sets polling simultaneously) without letting
// capacity decisions run on stale data.
const DefaultStateViewTTL = 5 * time.Second

// Snapshot is an atomic view of Orchard state used by scaling decisions and cleanup.
type Snapshot struct {
	VMs       []orchard.VM
	Workers   []orchard.Worker
	FetchedAt time.Time

	// workersByName is an index built once at snapshot construction so
	// ManagedVMsMatchingLabels can look up a VM's assigned worker without
	// scanning Workers per-call.
	workersByName map[string]*orchard.Worker
}

// StateView caches ListVMs+ListWorkers for a short TTL, shared across all
// bridges and the cleanup loop. Concurrent refreshes are coalesced via
// singleflight so a burst of HandleDesiredRunnerCount calls produces one
// round-trip to Orchard.
type StateView struct {
	client orchard.Client
	ttl    time.Duration

	mu         sync.Mutex
	snap       *Snapshot
	refreshing chan struct{} // non-nil while a refresh is in-flight
}

func NewStateView(client orchard.Client, ttl time.Duration) *StateView {
	if ttl <= 0 {
		ttl = DefaultStateViewTTL
	}
	return &StateView{client: client, ttl: ttl}
}

// Get returns a snapshot no older than ttl. If the current snapshot is fresh,
// it is returned without an API call. If stale or missing, one refresh is
// issued (concurrent callers wait on the same in-flight refresh).
//
// On refresh failure, Get returns the last known snapshot (possibly nil) with
// the error so callers can decide: scaling decisions skip, cleanup logs and
// continues.
func (s *StateView) Get(ctx context.Context) (*Snapshot, error) {
	s.mu.Lock()
	if s.snap != nil && time.Since(s.snap.FetchedAt) < s.ttl {
		snap := s.snap
		s.mu.Unlock()
		return snap, nil
	}

	// Join an in-flight refresh if one exists.
	if s.refreshing != nil {
		wait := s.refreshing
		s.mu.Unlock()
		select {
		case <-wait:
		case <-ctx.Done():
			return nil, ctx.Err()
		}
		s.mu.Lock()
		snap := s.snap
		s.mu.Unlock()
		if snap == nil {
			return nil, errors.New("orchard state refresh failed")
		}
		return snap, nil
	}

	// We lead the refresh.
	done := make(chan struct{})
	s.refreshing = done
	lastSnap := s.snap
	s.mu.Unlock()

	snap, err := s.refresh(ctx)

	s.mu.Lock()
	if err == nil {
		s.snap = snap
	}
	s.refreshing = nil
	close(done)
	if err != nil {
		s.mu.Unlock()
		return lastSnap, err
	}
	s.mu.Unlock()
	return snap, nil
}

// Invalidate forces the next Get to refresh. Call after any CreateVM/DeleteVM
// so the next scaling decision sees the mutation.
func (s *StateView) Invalidate() {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.snap = nil
}

func (s *StateView) refresh(ctx context.Context) (*Snapshot, error) {
	vms, err := s.client.ListVMs(ctx)
	if err != nil {
		return nil, err
	}
	workers, err := s.client.ListWorkers(ctx)
	if err != nil {
		return nil, err
	}
	return newSnapshot(vms, workers, time.Now()), nil
}

func newSnapshot(vms []orchard.VM, workers []orchard.Worker, at time.Time) *Snapshot {
	idx := make(map[string]*orchard.Worker, len(workers))
	for i := range workers {
		idx[workers[i].Name] = &workers[i]
	}
	return &Snapshot{
		VMs:           vms,
		Workers:       workers,
		FetchedAt:     at,
		workersByName: idx,
	}
}

// ManagedVMsForScaleSet returns managed VMs whose name matches the prefix
// generated by VMName for the given scale set. The 8-char suffix VMName
// appends is hex, so we also require the remainder to be hyphen-free —
// otherwise a VM for scale set "foo-large" would also match scale set "foo".
func (s *Snapshot) ManagedVMsForScaleSet(scaleSetName string) []orchard.VM {
	prefix := VMNamePrefixForScaleSet(scaleSetName)
	out := make([]orchard.VM, 0, len(s.VMs))
	for _, vm := range s.VMs {
		if !strings.HasPrefix(vm.Name, prefix) {
			continue
		}
		remainder := vm.Name[len(prefix):]
		if strings.Contains(remainder, "-") {
			continue
		}
		out = append(out, vm)
	}
	return out
}

// ManagedVMsMatchingLabels returns managed VMs that either run on a worker
// whose labels superset vmLabels, or — if the VM is not yet worker-assigned —
// whose own Labels superset vmLabels. The latter fallback covers pending VMs
// that have not been placed yet.
func (s *Snapshot) ManagedVMsMatchingLabels(vmLabels map[string]string) []orchard.VM {
	out := make([]orchard.VM, 0, len(s.VMs))
	for _, vm := range s.VMs {
		if !IsManagedVM(vm.Name) {
			continue
		}
		if vm.Worker != "" {
			w, ok := s.workersByName[vm.Worker]
			if ok && workerMatchesLabels(*w, vmLabels) {
				out = append(out, vm)
				continue
			}
		}
		if labelsSuperset(vm.Labels, vmLabels) {
			out = append(out, vm)
		}
	}
	return out
}

func labelsSuperset(have, want map[string]string) bool {
	for k, v := range want {
		if have[k] != v {
			return false
		}
	}
	return true
}
