package bridge

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/google/uuid"
)

const vmNamePrefix = "gha-orchard-"

var nonAlphanumHyphen = regexp.MustCompile(`[^a-z0-9-]`)

// IsManagedVM returns true if the VM name was generated by VMName.
func IsManagedVM(name string) bool {
	return strings.HasPrefix(name, vmNamePrefix)
}

// VMName generates a unique, k8s-label-safe VM name.
// Format: gha-{scaleSetName}-{shortUUID}, max 63 chars.
func VMName(scaleSetName string) string {
	short := uuid.New().String()[:8]
	name := fmt.Sprintf("%s%s", VMNamePrefixForScaleSet(scaleSetName), short)

	if len(name) > 63 {
		name = name[:63]
		name = strings.TrimRight(name, "-")
	}
	return name
}

// VMNamePrefixForScaleSet returns the deterministic name prefix VMName generates
// for a given scale set. Used to match existing Orchard VMs back to a scale set
// when hydrating state after a bridge restart.
func VMNamePrefixForScaleSet(scaleSetName string) string {
	sanitized := strings.ToLower(scaleSetName)
	sanitized = nonAlphanumHyphen.ReplaceAllString(sanitized, "-")
	sanitized = strings.Trim(sanitized, "-")
	return vmNamePrefix + sanitized + "-"
}

// StartupScript generates the bash script injected into the Orchard VM.
// The script configures the GitHub Actions runner with the JIT config and runs it.
//
// If dockerPort > 0, the Docker CLI is installed and DOCKER_HOST is set to
// the host daemon via TCP (host IP is auto-detected from the VM's default gateway).
func StartupScript(jitConfig string, dockerPort int) string {
	dockerSetup := ""
	if dockerPort > 0 {
		dockerSetup = fmt.Sprintf(`
# Install Docker CLI and connect to host Docker daemon via TCP
# stdin must be redirected: Orchard pipes the script to bash, and brew
# would otherwise consume the remaining script lines from stdin.
brew install docker docker-compose docker-buildx < /dev/null

# Register Compose/Buildx as Docker CLI plugins (brew installs them outside
# the default plugin search path).
mkdir -p ~/.docker
echo '{"cliPluginsExtraDirs":["/opt/homebrew/lib/docker/cli-plugins"]}' > ~/.docker/config.json

DOCKER_HOST_IP=$(route -n get default | awk '/gateway:/ {print $2}')
export DOCKER_HOST="tcp://${DOCKER_HOST_IP}:%d"
`, dockerPort)
	}

	return fmt.Sprintf(`#!/bin/bash
set -euo pipefail

export ACTIONS_RUNNER_INPUT_JITCONFIG="%s"

source ~/.zprofile
%s
# Download the latest GitHub Actions runner to avoid version deprecation.
DOWNLOAD_URL=$(curl -sS 'https://api.github.com/repos/actions/runner/releases/latest' \
  | grep -o '"browser_download_url": *"[^"]*actions-runner-osx-arm64-[0-9.]*\.tar\.gz"' \
  | cut -d'"' -f4)

RUNNER_DIR="$HOME/actions-runner"
rm -rf "$RUNNER_DIR" && mkdir -p "$RUNNER_DIR" && cd "$RUNNER_DIR"
curl -sL "$DOWNLOAD_URL" | tar xz

./run.sh
`, jitConfig, dockerSetup)
}
