package bridge

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/google/uuid"
)

const vmNamePrefix = "gha-orchard-"

var nonAlphanumHyphen = regexp.MustCompile(`[^a-z0-9-]`)

// IsManagedVM returns true if the VM name was generated by VMName.
func IsManagedVM(name string) bool {
	return strings.HasPrefix(name, vmNamePrefix)
}

// VMName generates a unique, k8s-label-safe VM name.
// Format: gha-{scaleSetName}-{shortUUID}, max 63 chars.
func VMName(scaleSetName string) string {
	sanitized := strings.ToLower(scaleSetName)
	sanitized = nonAlphanumHyphen.ReplaceAllString(sanitized, "-")
	sanitized = strings.Trim(sanitized, "-")

	short := uuid.New().String()[:8]
	name := fmt.Sprintf("%s%s-%s", vmNamePrefix, sanitized, short)

	if len(name) > 63 {
		name = name[:63]
		name = strings.TrimRight(name, "-")
	}
	return name
}

// StartupScript generates the bash script injected into the Orchard VM.
// The script configures the GitHub Actions runner with the JIT config and runs it.
//
// Docker support modes (mutually exclusive):
//   - dockerPort > 0: install Docker CLI and connect to the host daemon via TCP
//     (host IP is auto-detected from the VM's default gateway)
//   - nested: install Colima inside the VM (requires nested virtualization)
func StartupScript(jitConfig string, nested bool, dockerPort int) string {
	dockerSetup := ""
	if dockerPort > 0 {
		dockerSetup = fmt.Sprintf(`
# Install Docker CLI and connect to host Docker daemon via TCP
brew install docker docker-compose docker-buildx
DOCKER_HOST_IP=$(route -n get default | awk '/gateway:/ {print $2}')
export DOCKER_HOST="tcp://${DOCKER_HOST_IP}:%d"
`, dockerPort)
	} else if nested {
		dockerSetup = `
# Install Docker via Colima (requires nested virtualization / M3+)
brew install colima docker docker-compose docker-buildx
colima start --memory 4 --cpu 2
`
	}

	return fmt.Sprintf(`#!/bin/bash
set -euo pipefail

export ACTIONS_RUNNER_INPUT_JITCONFIG="%s"

source ~/.zprofile
%s
# Download the latest GitHub Actions runner to avoid version deprecation.
DOWNLOAD_URL=$(curl -sS 'https://api.github.com/repos/actions/runner/releases/latest' \
  | grep -o '"browser_download_url": *"[^"]*actions-runner-osx-arm64-[0-9.]*\.tar\.gz"' \
  | cut -d'"' -f4)

RUNNER_DIR="$HOME/actions-runner"
rm -rf "$RUNNER_DIR" && mkdir -p "$RUNNER_DIR" && cd "$RUNNER_DIR"
curl -sL "$DOWNLOAD_URL" | tar xz

./run.sh
`, jitConfig, dockerSetup)
}
